local r=bmd.scriptapp('Resolve')
local p=r:GetProjectManager():GetCurrentProject()
assert(p:GetName()=='UNCHAINED_V163_SYNTHETIC_20260923')
local t=p:GetCurrentTimeline()
local c=t:GetItemListInTrack('video',1)[2]:GetFusionCompByIndex(1)
local setting=bmd.readfile(arg[1])
assert(setting)
c:Paste(setting)
local macro=c:FindTool('UN_LyricMacro')
assert(macro)
print('MACRO_TYPE=' .. macro:GetAttrs().TOOLS_RegID)
print('BEFORE=' .. macro:GetInput('Text'))
macro:SetInput('Text','REUSABLE UNCHAINED')
print('AFTER=' .. macro:GetInput('Text'))
for _,m in pairs(c:GetToolList(false,'Merge')) do m.Foreground=macro.Output1 end
print('SAVE=' .. tostring(r:GetProjectManager():SaveProject()))
