#!/usr/bin/env python3
"""Verified literature evidence (numbers as stated on fetched pages, 2026-09-22). kind: peer_reviewed / industry_report / journalism / blog."""
import csv, os
OUT = os.path.join(os.path.dirname(__file__), "..", "data")
L = [
 dict(id="L01",citation="Léveillé Gauvin (2018) Musicae Scientiae 22(3)",url="https://journals.sagepub.com/doi/abs/10.1177/1029864917698010",verified="yes (abstract)",kind="peer_reviewed",market="US",sample="303 US top-10 singles 1986-2015; study 2: 60 popular vs 60 less popular 2015 songs same artists",feature="intro length; tempo; time-to-title; title words; self-focus",finding="Trends favour attention grabbing across 1986-2015; within-artist popular-vs-less-popular comparison showed no consistent pattern",numbers="see L02"),
 dict(id="L02",citation="Ohio State Univ. press release on Léveillé Gauvin (2017)",url="https://news.osu.edu/has-music-streaming-killed-the-instrumental-intro/",verified="yes",kind="secondary_summary_of_peer_reviewed",market="US",sample="303 US top-10 singles 1986-2015",feature="intro length; tempo; time-to-title",numbers="intro >20 s (mid-1980s) -> ~5 s (2015), '78 percent drop'; tempo +'roughly 8 percent'; time before title -'about 18 percent'",finding="intro shrinkage and tempo rise over 30 years; no within-artist streaming evidence"),
 dict(id="L03",citation="Klimmt et al. (2024) Convergence",url="https://journals.sagepub.com/doi/10.1177/13548565231208918",verified="yes (abstract)",kind="peer_reviewed",market="US/Spotify",sample="Billboard top-10 1986-2020 + Spotify top-10 2016-2020",feature="tempo; first-vocal time; time-to-title; title words; duration",numbers="none in abstract",finding="accelerated-composition trends 'mostly continued'; only weak evidence of a Spotify-specific booster"),
 dict(id="L04",citation="Interiano et al. (2018) R. Soc. Open Sci. 5:171274",url="https://escholarship.org/content/qt96b901t6/qt96b901t6.pdf",verified="yes (full PDF via eScholarship)",kind="peer_reviewed",market="UK",sample=">500,000 UK releases 1985-2015; 148,190 chart entries / 30,081 unique charting songs; 14,536 with AcousticBrainz features",feature="happiness, brightness, sadness, danceability, relaxedness, 'femaleness', timbre",numbers="prediction accuracy ~0.74 (features) / ~0.85 with superstar variable (as summarised)",finding="downward trend in happiness/brightness; upward danceability; successful songs happier, more party-like, less relaxed, more 'female' than average release"),
 dict(id="L05",citation="Askin & Mauskapf (2017) Am. Sociol. Rev. 82(5)",url="https://gwern.net/doc/culture/2017-askin.pdf",verified="yes (full PDF)",kind="peer_reviewed",market="US",sample="~27,000 Billboard Hot 100 songs 1958-2016; Echo Nest features",feature="genre-weighted typicality (cosine similarity to prior 52 weeks)",numbers="typicality mean .81 sd .06 range .26-.92",finding="inverted-U: highly typical songs less likely to reach top; optimal differentiation predicts peak position"),
 dict(id="L06",citation="Digital Music News summarising Quartz (2019-01-18)",url="https://www.digitalmusicnews.com/2019/01/18/streaming-music-shorter-songs-study/",verified="yes (secondary)",kind="journalism",market="US",sample="Billboard Hot 100 (Quartz)",feature="duration",numbers="avg length down 20 s in 5 years to 3:30; 6% of 2018 hits <=2:30",finding="hits shortening 2013-2018"),
 dict(id="L07",citation="Chartmetric 'Are Songs Actually Getting Shorter?' (2025)",url="https://hmc.chartmetric.com/shorter-songs-trend-streaming-history/",verified="yes",kind="industry_report",market="global Spotify charts",sample="Spotify charting songs 2019-2024",feature="duration",numbers="2024 avg ~3:00, ~15 s shorter than 2023, ~30 s shorter than 2019; 1990s 4:14; 2018->2024 all major genres -17 s+, hip-hop & Latin -29 s; ~20% of 2024 Grammy songs <3:00",finding="continued shortening; genre-dependent"),
 dict(id="L08",citation="UCLA DataRes / Statista (160K Spotify tracks 1921-2020)",url="https://ucladatares.medium.com/spotify-trends-analysis-129c8a31cf04",verified="yes",kind="blog_dataset",market="global Spotify catalog (not hits)",sample="~160,000 tracks",feature="duration",numbers="mean 195 s (1930), 259 s (1990), 197 s (2020)",finding="peak length ~1990 then decline; catalog-wide, not success-conditioned"),
 dict(id="L09",citation="Hit Songs Deconstructed Trend Report Q3 2014",url="https://www.hitsongsdeconstructed.com/hsd_wire/the-hit-songs-deconstructed-trend-report/",verified="yes",kind="industry_report",market="US",sample="20 Billboard top-10 songs Q3 2014 (vs Q2 2014)",feature="duration; intro length; first-chorus time",numbers="length 3:52->3:33; 4:00+ share 44%->20%; intro avg 12 s->9 s; intros 1-9 s: 25%->53%; first chorus avg 0:42->0:33; first chorus 0:20-0:39: 15% (Q1)->47% (Q3); first chorus >=1:00: 5%",finding="very small n; direction consistent with L02"),
 dict(id="L10",citation="PA news agency analysis via Irish News (2022-11-14)",url="https://www.irishnews.com/magazine/entertainment/2022/11/14/news/shorter_slower_and_fewer_key_changes_how_number_ones_changed_over_70_years-2904307/",verified="yes",kind="journalism",market="UK",sample="1,404 UK number ones 1952-2022",feature="duration; key changes; fade-outs; minor keys",numbers="length ~3:00 (1967) -> ~4:00 (1984) -> ~3:00 (2022); key changes 43% (1953), 29% (1986), one in past nine years; fade-outs 93% (1971), 100% (1983), 0 (2011), 23 since; minor key 58% (2019), 55% (2020), 55% (2022)",finding="modern UK #1s: ~3 min, majority minor, no key changes, hard endings"),
 dict(id="L11",citation="Dalla Riva, 'Are Pop Songs Getting Sadder?' (Can't Get Much Higher)",url="https://www.cantgetmuchhigher.com/p/are-pop-songs-getting-sadder",verified="yes",kind="blog_dataset",market="US",sample="every Billboard Hot 100 #1 since 1958 (>1,100; per NPR)",feature="mode; tempo",numbers="minor-key share 25% (1958-2000) vs 55% (2000-2010s era as described); #1s <100 BPM: 43% (2010s) vs 25% (1960-1989)",finding="minor-key majority and slower tempos among recent US #1s"),
 dict(id="L12",citation="NPR 'Where did all the key changes go?' (2022-11-30)",url="https://www.npr.org/2022/11/30/1139707179/where-did-all-the-key-changes-go",verified="yes",kind="journalism",market="US",sample="Billboard #1s since 1958 (Dalla Riva)",feature="key changes",numbers="~25% of #1s had key changes 1960s-1990s; 2010-2020 only one ('Sicko Mode')",finding="key-change device nearly absent in modern #1s"),
 dict(id="L13",citation="Hooktheory blog 'I analyzed the chords of 1300 popular songs'",url="https://www.hooktheory.com/blog/i-analyzed-the-chords-of-1300-popular-songs-for-patterns-this-is-what-i-found/",verified="yes",kind="blog_dataset",market="mixed",sample=">1,300 Hooktheory entries",feature="key; chord transitions",numbers="C major and A minor most common; Bb only 4%; after Em in C-major songs 93% go to Am or F",finding="key distribution skewed to guitar/piano-friendly keys; strong diatonic transition regularities"),
 dict(id="L14",citation="Music By Mattie 'I analyzed 3,054 hit songs'",url="https://musicbymattie.com/blog/i-analyzed-3-054-hit-songs-to-find-what-1s-do-differently",verified="yes",kind="blog_dataset",market="US",sample="3,054 Billboard hits over 35 years; #1 vs non-#1",feature="mode; tempo; lyric density; vocal dynamic range",numbers="#1s 65% major/35% minor vs non-#1 63/37; #1s 117 BPM vs 120; #1s ~14% more words",finding="mode and tempo differences between #1 and other charting songs are small"),
 dict(id="L15",citation="Rolling Stone 'Pop Hits Were Really Slow (Again) in 2018' (Soundfly data)",url="https://www.rollingstone.com/music/music-news/pop-hits-2018-slow-tempo-788045/",verified="yes",kind="journalism",market="US/Spotify",sample="every Billboard top-5 song 2017 & 2018; Spotify top-25 2012 vs 2017",feature="tempo",numbers="avg 93.2 BPM (2017), 92.6 BPM (2018); modal range 79-80 (2017), 78-79 (2018); Spotify top-25 avg fell 23 BPM 2012->2017 to 90.5",finding="late-2010s hits cluster ~78-95 BPM (half-time feel likely; perceived pulse ambiguity not resolved by source)"),
 dict(id="L16",citation="Carter & von Appen (2025) Intégral 38",url="https://theory.esm.rochester.edu/integral/38-2025/carter-von-appen/",verified="yes",kind="peer_reviewed",market="US",sample="255 + 168 Hot 100 recordings 1966-1995; Melodyne tempo maps",feature="tempo variability (CV)",numbers="median CV 0.76; yearly median CV 1.51 (1972) -> 0.03 (1994)",finding="steep decline in tempo variability from 1979; modern hits are grid-tight"),
 dict(id="L17",citation="Colin Munroe 'Chorus Start Time' (Substack)",url="https://colinmunroe.substack.com/p/chorus-start-time",verified="yes (informal)",kind="blog_dataset",market="US",sample="~2,500 Hot 100 songs 2021-2024; chorus times via LLM (method weak)",feature="first-chorus time",numbers="best-performing group: chorus at 30-60 s; immediate-chorus songs worst; author states shift 'lacks statistical significance'",finding="weak evidence that very early chorus is not optimal; low confidence"),
 dict(id="L18",citation="Choudhury, Bhagwan & Bali (2013) ISMIR",url="https://archives.ismir.net/ismir2013/paper/000103.pdf",verified="yes (full PDF)",kind="peer_reviewed",market="India (Hindi film)",sample="310 Bollywood hit songs 1953-2013 from yearly top-50 lists; expert scale labelling",feature="melodic scale (thaat)",numbers="~25% Asavari (natural minor-type), ~25% Bilawal (major), Bhairavi+Kafi+Khamaj ~25%, pentatonic 8%, Kalyan 4%, none in Bhairav/Marwa/Todi",finding="Hindi hits split roughly evenly between minor-type and major scales; Kalyan (Lydian) declined since 1960s; Bhairavi rose"),
 dict(id="L19",citation="'Exploring the Evolutionary Change in Bollywood Lyrics over the Last Two Decades' (Academia.edu)",url="https://www.academia.edu/34373535/",verified="yes",kind="grey_literature",market="India",sample="300 songs 1995-2005 vs 2006-2015",feature="lyric language mix",numbers="'hai' 18.86% of top-word occurrences; 'baby' most frequent English word 11.20%; English usage rose",finding="Hinglish increase in Bollywood lyrics"),
 dict(id="L20",citation="Scroll.in 'Before size mattered' (2019)",url="https://scroll.in/reel/917102/",verified="yes",kind="journalism",market="India",sample="anecdotal examples",feature="duration",numbers="1970s-80s examples 8+ min; today soundtrack 'barely crosses 25 minutes', songs 'often fade out after the four-minute mark'",finding="Hindi film songs shortened; anecdotal"),
 dict(id="L21",citation="Hamilton & Pearce (2024) Sci. Rep. 14:14749",url="https://www.nature.com/articles/s41598-024-64571-x",verified="yes",kind="peer_reviewed",market="US",sample="366 songs (top-5 year-end 1950-2022), 1,131 MIDI melodies",feature="melodic complexity, note density, interval size, pitch range",numbers="post-2000 ~2.8 notes/s; mean interval ~2.0 semitones; two-thirds of pitches within a 5.5-semitone range",finding="revolutions 1975 & 2000 toward lower melodic complexity, higher note density, narrow tessitura"),
 dict(id="L22",citation="Hamilton, Clemente, Hall & Pearce (2024) BiMMuDa, TISMIR",url="https://doaj.org/article/1ff1ffc2366c41748dc7dad8c720e7aa",verified="yes (abstract)",kind="peer_reviewed",market="US",sample="371 melodies top-5/year 1950-2022",feature="chorus vs verse melody",numbers="none in abstract",finding="choruses have fewer notes, lower note density, larger intervals than verses"),
 dict(id="L23",citation="Morris (2017) 'Are Pop Lyrics Getting More Repetitive?' The Pudding",url="https://pudding.cool/2017/05/song-repetition/",verified="yes",kind="blog_dataset",market="US",sample="15,000 Hot 100 songs 1958-2017; Lempel-Ziv compressibility",feature="lyric repetition",numbers="1960 avg 45.7% compressible; 2014 compresses 22% more efficiently; top-10 songs more repetitive than the rest in every year",finding="repetition rises over time and is higher among top-10 songs (association)"),
 dict(id="L24",citation="Nunes, Ordanini & Valsesia (2015) J. Consumer Psychol. 25(2)",url="https://www.sciencedirect.com/science/article/abs/pii/S1057740814001260",verified="yes (abstract)",kind="peer_reviewed",market="US",sample="Hot 100 1958-2012; #1s vs never above #90",feature="chorus repetition; word repetition",numbers="coefficients not in abstract",finding="more chorus repetition -> higher probability of #1 and faster climb; excessive word repetition offsets the benefit"),
]
with open(os.path.join(OUT,"LITERATURE_EVIDENCE.csv"),"w",newline="",encoding="utf-8") as f:
    w=csv.DictWriter(f,fieldnames=list(L[0].keys())); w.writeheader(); [w.writerow(x) for x in L]
print(len(L),"literature rows")
