"""Explicit, auditable campaign state machine (deterministic transitions)."""
from enum import Enum


class State(str, Enum):
    SOURCE_READY = "SOURCE_READY"
    PREPROCESSING = "PREPROCESSING"
    EDIT_BUILDING = "EDIT_BUILDING"
    SANDBOX_PREVIEW_RENDERING = "SANDBOX_PREVIEW_RENDERING"
    SANDBOX_PREVIEW_READY = "SANDBOX_PREVIEW_READY"
    AWAITING_CREATIVE_APPROVAL = "AWAITING_CREATIVE_APPROVAL"
    CREATIVE_APPROVED = "CREATIVE_APPROVED"
    CREATIVE_REJECTED = "CREATIVE_REJECTED"
    FROZEN_JSON_READY = "FROZEN_JSON_READY"
    PRODUCTION_AUTHORIZED = "PRODUCTION_AUTHORIZED"
    PRODUCTION_RENDERING = "PRODUCTION_RENDERING"
    PRODUCTION_RENDER_READY = "PRODUCTION_RENDER_READY"
    TECH_QC_RUNNING = "TECH_QC_RUNNING"
    TECH_QC_PASS = "TECH_QC_PASS"
    TECH_QC_FAIL = "TECH_QC_FAIL"
    AWAITING_FINAL_VIDEO_APPROVAL = "AWAITING_FINAL_VIDEO_APPROVAL"
    FINAL_VIDEO_APPROVED = "FINAL_VIDEO_APPROVED"
    FINAL_VIDEO_REJECTED = "FINAL_VIDEO_REJECTED"
    DERIVATIVES_BUILDING = "DERIVATIVES_BUILDING"
    DERIVATIVES_READY = "DERIVATIVES_READY"
    PACKAGING_BUILDING = "PACKAGING_BUILDING"
    PACKAGING_READY = "PACKAGING_READY"
    AWAITING_PUBLISH_APPROVAL = "AWAITING_PUBLISH_APPROVAL"
    PUBLISH_APPROVED = "PUBLISH_APPROVED"
    PUBLISH_REJECTED = "PUBLISH_REJECTED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    ANALYTICS_ACTIVE = "ANALYTICS_ACTIVE"
    HOLD = "HOLD"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


# Allowed forward transitions. HOLD/FAILED reachable from any state (see can_transition).
TRANSITIONS = {
    State.SOURCE_READY: [State.PREPROCESSING, State.EDIT_BUILDING],
    State.PREPROCESSING: [State.EDIT_BUILDING],
    State.EDIT_BUILDING: [State.SANDBOX_PREVIEW_RENDERING, State.FROZEN_JSON_READY],
    State.SANDBOX_PREVIEW_RENDERING: [State.SANDBOX_PREVIEW_READY],
    State.SANDBOX_PREVIEW_READY: [State.AWAITING_CREATIVE_APPROVAL],
    State.AWAITING_CREATIVE_APPROVAL: [State.CREATIVE_APPROVED, State.CREATIVE_REJECTED],
    State.CREATIVE_REJECTED: [State.EDIT_BUILDING, State.ARCHIVED],
    State.CREATIVE_APPROVED: [State.FROZEN_JSON_READY],
    State.FROZEN_JSON_READY: [State.PRODUCTION_AUTHORIZED],
    State.PRODUCTION_AUTHORIZED: [State.PRODUCTION_RENDERING],
    State.PRODUCTION_RENDERING: [State.PRODUCTION_RENDER_READY, State.TECH_QC_FAIL],
    State.PRODUCTION_RENDER_READY: [State.TECH_QC_RUNNING],
    State.TECH_QC_RUNNING: [State.TECH_QC_PASS, State.TECH_QC_FAIL],
    State.TECH_QC_PASS: [State.AWAITING_FINAL_VIDEO_APPROVAL],
    State.TECH_QC_FAIL: [State.EDIT_BUILDING, State.PRODUCTION_AUTHORIZED, State.HOLD],
    State.AWAITING_FINAL_VIDEO_APPROVAL: [State.FINAL_VIDEO_APPROVED, State.FINAL_VIDEO_REJECTED],
    State.FINAL_VIDEO_REJECTED: [State.EDIT_BUILDING, State.ARCHIVED],
    State.FINAL_VIDEO_APPROVED: [State.DERIVATIVES_BUILDING],
    State.DERIVATIVES_BUILDING: [State.DERIVATIVES_READY, State.HOLD],
    State.DERIVATIVES_READY: [State.PACKAGING_BUILDING],
    State.PACKAGING_BUILDING: [State.PACKAGING_READY, State.HOLD],
    State.PACKAGING_READY: [State.AWAITING_PUBLISH_APPROVAL],
    State.AWAITING_PUBLISH_APPROVAL: [State.PUBLISH_APPROVED, State.PUBLISH_REJECTED],
    State.PUBLISH_REJECTED: [State.PACKAGING_READY, State.ARCHIVED],
    State.PUBLISH_APPROVED: [State.PUBLISHING],
    State.PUBLISHING: [State.PUBLISHED, State.HOLD],
    State.PUBLISHED: [State.ANALYTICS_ACTIVE],
    State.ANALYTICS_ACTIVE: [State.ARCHIVED],
    State.HOLD: [],   # HOLD is resolved explicitly via resume() to last_successful_state
    State.FAILED: [],
    State.ARCHIVED: [],
}

# States that represent a human decision gate.
GATE_STATES = {
    State.AWAITING_CREATIVE_APPROVAL,
    State.AWAITING_FINAL_VIDEO_APPROVAL,
    State.AWAITING_PUBLISH_APPROVAL,
}


def can_transition(src: State, dst: State) -> bool:
    if dst in (State.HOLD, State.FAILED):
        return True  # safety routing always allowed
    return dst in TRANSITIONS.get(src, [])
